version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "85:80"
    networks:
      - local
    volumes:
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./public:/var/www/html
        
  phpfpm:
    image: php:8.1-fpm
    networks:
      - local
    volumes:
      - ./public:/var/www/html
#     - ./nginx/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
  mysql:
    image: mariadb:10.8.2
    ports:
      - "3306:3306"
    networks:
      - local
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test123
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
       - 8080:80
    environment:
        MYSQL_USERNAME: test
        MYSQL_ROOT_PASSWORD: test123
        PMA_HOST: mysql
    networks:
      - local
networks:
  local:
    driver: bridge  
